name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.3
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Lint with Ruff
      run: |
        source venv/bin/activate
        pip install ruff
        ruff app
